spells_list = [
    core_spell(
        "Fireball", "@\"", SpellSubtype.Core,
        "#e52", "#000",
        "",
        10, DmgType.Fire,
        7, 3, Shape.Diamond,
        25,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Searing Touch", "\">", SpellSubtype.Core,
        "#f52", "#000",
        "Doubles this core's final damage value.",
        40, DmgType.Fire,
        2, 1, Shape.Diamond,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Flame Nova", "X\"", SpellSubtype.Core,
        "#e84", "#000",
        "Gains 5 times this core's radius as damage.",
        10, DmgType.Fire,
        0, 4, Shape.Diamond,
        50,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Flarefrost Beam", "=>", SpellSubtype.Core,
        "#e58", "#000",
        "Deals Ice damage equal to this core's damage value at every tile affected.",
        12, DmgType.Fire,
        9, 1, Shape.Line,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Cleansing Fire", "!\"", SpellSubtype.Core,
        "#fd4", "#000",
        "Half of all Fire damage caused by this core is redealt as Holy damage.",
        14, DmgType.Fire,
        8, 2, Shape.Diamond,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Ice Ball", "@>", SpellSubtype.Core,
        "#aff", "#000",
        "Deals Physical damage equal to this core's damage value at every tile affected.",
        6, DmgType.Ice,
        8, 2, Shape.Diamond,
        25,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Snap Freeze", "V^", SpellSubtype.Core,
        "#cff", "#000",
        "Applies Freeze for 3 turns to the unit at the target position.",
        6, DmgType.Ice,
        10, 1, Shape.Diamond,
        20,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Chilling Burst", "«>", SpellSubtype.Core,
        "#aff", "#000",
        "Applies Freeze for 2 turns to any unit taking Ice damage from this core.",
        9, DmgType.Ice,
        0, 7, Shape.Diamond,
        60,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Frostbite", "<^", SpellSubtype.Core,
        "#9bf", "#000",
        "Any instance of Ice damage caused by this core causes Dark damage equal to the core's damage value at the same position.",
        6, DmgType.Ice,
        7, 1, Shape.Diamond,
        50,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Absolute Zero", "^!", SpellSubtype.Core,
        "#bff", "#000",
        "Applies Freeze for 6 turns to the unit at the target position.",
        25, DmgType.Ice,
        0, 32, Shape.Diamond,
        250,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Lightning Bolt", "&>", SpellSubtype.Core,
        "#ff3", "#000",
        "",
        13, DmgType.Lightning,
        10, 1, Shape.Line,
        17,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Arc Lightning", "&*", SpellSubtype.Core,
        "#ff3", "#000",
        "Has an arc value of 3.",
        12, DmgType.Lightning,
        10, 1, Shape.Line,
        35,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Chain Lightning", "&/", SpellSubtype.Core,
        "#ff3", "#000",
        "Has a chain value of 4.",
        10, DmgType.Lightning,
        10, 1, Shape.Line,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Hypercharge", "^&", SpellSubtype.Core,
        "#ff6", "#000",
        "All damaged units take and deal 50% more Lightning damage for 16 turns.",
        6, DmgType.Lightning,
        6, 3, Shape.Circle,
        75,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Spark", "-*", SpellSubtype.Core,
        "#ff0", "#127",
        "Casts another core at the point this core was targeted.",
        1, DmgType.Lightning,
        12, 0, Shape.Diamond,
        -15,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    modifier(
        "15", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "16", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "17", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "18", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "19", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "20", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "21", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "22", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "23", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "24", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "25", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "26", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "27", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "28", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "29", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "30", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "31", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "32", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "33", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "34", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "35", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "36", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "37", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "38", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "39", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "40", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "41", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "42", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "43", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "44", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "45", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "46", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "47", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "48", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "49", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Damage Plus I", "D+", SpellSubtype.Stats,
        "#c44", "#03f",
        "Increases the core's damage value by 5.",
        15,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Damage Plus II", "D*", SpellSubtype.Stats,
        "#c44", "#03f",
        "Increases the core's damage value by 15.",
        40,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Damage Overcharge", "D!", SpellSubtype.Stats,
        "#f44", "#03f",
        "Locks the radius of the core to 1. The core's damage value is increased by 5 times its radius before this reduction.",
        70,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Radius Plus I", "R+", SpellSubtype.Stats,
        "#4cf", "#03f",
        "Increases the core's radius by 1.",
        20,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Radius Plus II", "R*", SpellSubtype.Stats,
        "#4cf", "#03f",
        "Increases the core's radius by 2.",
        30,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Range Plus I", "N+", SpellSubtype.Stats,
        "#4d4", "#03f",
        "Increases the core's range by 2.",
        12,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Range Plus II", "N*", SpellSubtype.Stats,
        "#4d4", "#03f",
        "Increases the core's range by 5.",
        20,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Orbital Mirroring", "N!", SpellSubtype.Stats,
        "#2f2", "#03f",
        "Increases the core's range by 64.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Projection", ">~", SpellSubtype.Stats,
        "#fff", "#03f",
        "Allows the core to ignore line of sight and collision for targeting and effects.",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Undercharging I", "P-", SpellSubtype.Stats,
        "#caa", "#03f",
        "Reduces the core's damage value by 7 and its radius by 1, but costs [#4df]negative mana[clear].",
        -25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Undercharging II", "p.", SpellSubtype.Stats,
        "#caa", "#03f",
        "Reduces the core's damage value by 13 and its radius by 2, but costs [#4df]negative mana[clear].",
        -60,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Power Focus", "#!", SpellSubtype.Stats,
        "#e6e", "#03f",
        "Reduces the core's range by 6, but increases its damage value by 25.",
        25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Unbounded Energy", "^M", SpellSubtype.Stats,
        "#6ff", "#03f",
        "Increases the core's damage value by 10% of the caster's current mana, but also makes it remove 10% of the caster's current mana on cast.",
        10,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Synergistic Arcana", "x+", SpellSubtype.Stats,
        "#e6e", "#03f",
        "Multiplies the effect of previous modifiers on the core's stats by 1.25x.",
        75,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Antisynergy", "x-", SpellSubtype.Stats,
        "#93f", "#03f",
        "Multiplies the effect of previous modifiers on the core's stats by 0.75x.",
        5,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Random Damage", "D?", SpellSubtype.Stats,
        "#fff", "#03f",
        "Increases the core's damage value by a random number from -100 to 100.",
        33,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Zenith Arcana I", "X*", SpellSubtype.Stats,
        "#0ef", "#03f",
        "Increases the core's damage value by 50, its radius by 3 and its range by 8.",
        600,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Zenith Arcana II", "X#", SpellSubtype.Stats,
        "#4ff", "#03f",
        "Increases the core's damage value by 150, its radius by 5 and its range by 12.",
        2000,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "68", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "69", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "70", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "71", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "72", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "73", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "74", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "75", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "76", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "77", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "78", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "79", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Freezing Fire", "\"^", SpellSubtype.Damage,
        "#e52", "#23f",
        "Half of all Fire damage from the core is redealt as Ice damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Crystallized Flame", "\"«", SpellSubtype.Damage,
        "#e52", "#23f",
        "Half of all Fire damage from the core is redealt as Arcane damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chaotic Immolation", "\"%", SpellSubtype.Damage,
        "#e52", "#23f",
        "Half of all Fire damage from the core is redealt as Chaos damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Sacred Flames", "\"*", SpellSubtype.Damage,
        "#e52", "#23f",
        "Half of all Fire damage from the core is redealt as Holy damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Charged Ice", "^&", SpellSubtype.Damage,
        "#aff", "#23f",
        "Half of all Ice damage from the core is redealt as Lightning damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Crystalline Frost", "^«", SpellSubtype.Damage,
        "#aff", "#23f",
        "Half of all Ice damage from the core is redealt as Arcane damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Stifling Frost", "^#", SpellSubtype.Damage,
        "#aff", "#23f",
        "Half of all Ice damage from the core is redealt as Dark damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Arcane Conductance", "&«", SpellSubtype.Damage,
        "#aff", "#23f",
        "Half of all Lightning damage from the core is redealt as Arcane damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Cracklevoid", "&#", SpellSubtype.Damage,
        "#ff3", "#23f",
        "Half of all Lightning damage from the core is redealt as Dark damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Heavenstrike", "&*", SpellSubtype.Damage,
        "#ff3", "#23f",
        "Half of all Lightning damage from the core is redealt as Holy damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Mind Bolts", "&{", SpellSubtype.Damage,
        "#ff3", "#23f",
        "Half of all Lightning damage from the core is redealt as Psychic damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Crystallized Sorcery", "»^", SpellSubtype.Damage,
        "#f49", "#23f",
        "Half of all Arcane damage from the core is redealt as Ice damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Dark Magic", "»#", SpellSubtype.Damage,
        "#f49", "#23f",
        "Half of all Arcane damage from the core is redealt as Dark damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Mind Magic", "»{", SpellSubtype.Damage,
        "#f49", "#23f",
        "Half of all Arcane damage from the core is redealt as Psychic damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Falcon Fist", "=\"", SpellSubtype.Damage,
        "#ddd", "#23f",
        "Half of all Physical damage from the core is redealt as Fire damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Lightning Fist", "=&", SpellSubtype.Damage,
        "#ddd", "#23f",
        "Half of all Physical damage from the core is redealt as Lightning damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Double Hit", "=2", SpellSubtype.Damage,
        "#ddd", "#23f",
        "All Physical damage from the core is redealt as Physical damage. This damage cannot trigger further effects.",
        150,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Shadow Strike", "=#", SpellSubtype.Damage,
        "#ddd", "#23f",
        "Half of all Physical damage from the core is redealt as Dark damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Pure Strike", "=*", SpellSubtype.Damage,
        "#ddd", "#23f",
        "Half of all Physical damage from the core is redealt as Holy damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Telekinesis", "={", SpellSubtype.Damage,
        "#ddd", "#23f",
        "Half of all Physical damage from the core is redealt as Psychic damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Blackflame", "#\"", SpellSubtype.Damage,
        "#95a", "#23f",
        "Half of all Dark damage from the core is redealt as Fire damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Deathly Frost", "#^", SpellSubtype.Damage,
        "#95a", "#23f",
        "Half of all Dark damage from the core is redealt as Ice damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Demonic Dark", "#%", SpellSubtype.Damage,
        "#95a", "#23f",
        "Half of all Dark damage from the core is redealt as Chaos damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Sacred Magic", "*«", SpellSubtype.Damage,
        "#ffa", "#23f",
        "Half of all Holy damage from the core is redealt as Arcane damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Apostasy", "*#", SpellSubtype.Damage,
        "#ffa", "#23f",
        "Half of all Holy damage from the core is redealt as Dark damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chromatic Catalyst", "O)", SpellSubtype.Damage,
        "#fff", "#23f",
        "Redeals all native damage from the core as every other damage type, split equally between each type.",
        200,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Null Magic", "-)", SpellSubtype.Damage,
        "#80a", "#23f",
        "Deals [#4df]negative[clear] damage equivalent to every instance of damage the core caused.",
        25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Hand of Fate", "O?", SpellSubtype.Damage,
        "#fff", "#23f",
        "Half of all native damage from the core is redealt as a random other damage type.",
        75,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chromatic Convergence", "O>", SpellSubtype.Damage,
        "#fff", "#23f",
        "Redeals all native damage from the core as the damage type the damaged unit is least resistant to, not including the core's own damage type.",
        250,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chromatic Divergence", "O<", SpellSubtype.Damage,
        "#fff", "#23f",
        "Redeals all native damage from the core as the damage type the damaged unit is most resistant to, not including the core's own damage type.",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "110", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "111", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "112", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "113", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "114", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "115", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "116", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "117", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "118", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "119", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "120", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "121", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "122", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "123", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "124", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Add Target Trigger", "+*", SpellSubtype.Trigger,
        "#aa0", "#26f",
        "Makes the core cast the next core at the point it was targeted.",
        25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Add Tile Trigger", "+x", SpellSubtype.Trigger,
        "#aa0", "#26f",
        "Makes the core cast a copy of the next core at every tile the core affected.",
        500,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Add Damage Trigger", "+;", SpellSubtype.Trigger,
        "#aa0", "#26f",
        "Makes the core cast a copy of the next core at every instance of damage the core caused.",
        400,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "128", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "129", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "130", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "131", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "132", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "133", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "134", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Positional", "##", SpellSubtype.Shape,
        "#fff", "#441",
        "Allows the core to target [#4df]a position on the ground[clear].",
        90,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Unit Target", "##", SpellSubtype.Shape,
        "#fff", "#441",
        "Allows the core to target [#4df]a specific unit[clear].",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Self Target", "##", SpellSubtype.Shape,
        "#fff", "#441",
        "Allows the core to target [#4df]the area around the caster[clear].",
        25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Self Position", "##", SpellSubtype.Shape,
        "#fff", "#441",
        "Allows the core to target [#4df]at the caster's position[clear].",
        10,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "139", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "140", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "141", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "142", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "143", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "144", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Behind the Back", "<$", SpellSubtype.Multicast,
        "#fff", "#06b",
        "Casts a copy of the core behind the user.",
        120,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "146", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "147", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "148", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "149", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "150", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "151", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Multicast x4", ">4", SpellSubtype.Multicast,
        "#6f6", "#06b",
        "Adds 4 to the core's multicast value.",
        350,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "153", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "154", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "155", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "156", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "157", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "158", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chain Spell", "/>", SpellSubtype.Multicast,
        "#fff", "#06b",
        "Adds 4 to the core's chain value.",
        350,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Arc Spell", "*>", SpellSubtype.Multicast,
        "#ff0", "#06b",
        "Adds 4 to the core's arc value.",
        300,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "161", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "162", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "163", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "164", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "165", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "166", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "167", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "168", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "169", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Conjure Mana", "##", SpellSubtype.Misc,
        "#fff", "#265",
        "Restores 15 mana to the caster when the core is cast.",
        10,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Hardening Enchantment", "##", SpellSubtype.Misc,
        "#fff", "#265",
        "Native damage caused by the core applies 3 turns of Resistance (core damage type)",
        40,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Intensifying Enchantment", "##", SpellSubtype.Misc,
        "#fff", "#265",
        "Native damage caused by the core applies 4 turns of Polarity (core damage type)",
        75,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chromatic Impact", "##", SpellSubtype.Misc,
        "#fff", "#265",
        "Any unit at the core's target position will receive Polarity of every damage type for 10 turns.",
        125,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Cleanse", "##", SpellSubtype.Misc,
        "#fff", "#265",
        "Any unit damaged by the core will have all active effects removed from it.",
        40,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "175", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "176", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "177", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "178", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "179", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "180", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "181", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "182", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "183", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "184", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "185", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "186", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "187", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "188", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "189", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "190", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "191", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "192", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "193", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "194", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "195", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "196", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "197", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "198", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "199", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    core_spell(
        "Gun", "%=", SpellSubtype.Red,
        "#fff", "#f00",
        "",
        5000, DmgType.Physical,
        30, 1, Shape.Line,
        50,
        SpellTargeting.Positional,
        [Teams.ENEMY]
    ),

    modifier(
        "Uncontrolled Multicast x16", "!F", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "Casts a copy of the core sixteen times, moving the target by a random number of tiles up to the core's final radius + 1 each time.",
        200,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    core_spell(
        "All Elements", "!!", SpellSubtype.Red,
        "#fff", "#f00",
        "all at once. testing",
        99999, DmgType.Physical,
        1, 40, Shape.Diamond,
        0,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Pea Spell", "!!", SpellSubtype.Red,
        "#fff", "#f00",
        "pea spell",
        73, DmgType.Chaos,
        10, 3, Shape.Circle,
        2,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "summon GUY", "@»", SpellSubtype.Red,
        "#fff", "#f00",
        "Summon \"Guy\" at the target position.",
        25, DmgType.Dark,
        10, 5, Shape.Circle,
        120,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    modifier(
        "205", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "206", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "207", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "208", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "209", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "210", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "211", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "212", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "213", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "214", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "215", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "216", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "217", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "218", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "219", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "220", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "221", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "222", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "223", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "224", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "225", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "226", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "227", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "228", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "229", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "230", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "231", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "232", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "233", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "234", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "235", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "236", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "237", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "238", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "239", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "240", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "241", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "242", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "243", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "244", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "245", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "246", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "247", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "248", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "249", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "250", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "251", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "252", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "253", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "254", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "255", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "256", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "257", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "258", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "259", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "260", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "261", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "262", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "263", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "264", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "265", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "266", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "267", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "268", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "269", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "270", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "271", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "272", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "273", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "274", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "275", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "276", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "277", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "278", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "279", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "280", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "281", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "282", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "283", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "284", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "285", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "286", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "287", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "288", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "289", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "290", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "291", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "292", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "293", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "294", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "295", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "296", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "297", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "298", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "299", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "300", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),


]