spells_list = [
    core_spell(
        "Fireball", "@\"", SpellSubtype.Core,
        "#e52", "#000",
        "",
        10, DmgType.Fire,
        7, 3, Shape.Diamond,
        25,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Searing Touch", "\">", SpellSubtype.Core,
        "#f52", "#000",
        "Doubles this core's final damage value.",
        40, DmgType.Fire,
        2, 1, Shape.Diamond,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Flame Nova", "X\"", SpellSubtype.Core,
        "#e84", "#000",
        "Gains 5 times this core's final radius as damage.",
        10, DmgType.Fire,
        0, 4, Shape.Diamond,
        50,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Flarefrost Beam", "=>", SpellSubtype.Core,
        "#e58", "#000",
        "Deals Ice damage equal to this core's damage value at every tile affected.",
        12, DmgType.Fire,
        9, 1, Shape.Line,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Cleansing Fire", "!\"", SpellSubtype.Core,
        "#fd4", "#000",
        "Half of all Fire damage caused by this core is redealt as Holy damage.",
        14, DmgType.Fire,
        8, 2, Shape.Diamond,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Ice Ball", "@>", SpellSubtype.Core,
        "#aff", "#000",
        "Deals Physical damage equal to this core's damage value at every tile affected.",
        6, DmgType.Ice,
        8, 2, Shape.Diamond,
        25,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Snap Freeze", "V^", SpellSubtype.Core,
        "#cff", "#000",
        "Applies Frozen for 3 turns to the unit at the target position.",
        6, DmgType.Ice,
        10, 1, Shape.Diamond,
        20,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Chilling Burst", "«>", SpellSubtype.Core,
        "#aff", "#000",
        "Applies Frozen for 2 turns to any unit taking Ice damage from this core.",
        9, DmgType.Ice,
        0, 7, Shape.Diamond,
        60,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Frostbite", "<^", SpellSubtype.Core,
        "#9bf", "#000",
        "Any instance of Ice damage caused by this core causes Dark damage equal to this core's damage value at the same position.",
        6, DmgType.Ice,
        7, 1, Shape.Diamond,
        50,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Absolute Zero", "^!", SpellSubtype.Core,
        "#bff", "#000",
        "Applies Freeze for 6 turns to the unit at the center of the burst.",
        20, DmgType.Ice,
        0, 12, Shape.Diamond,
        140,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Lightning Bolt", "&>", SpellSubtype.Core,
        "#ff3", "#000",
        "",
        13, DmgType.Lightning,
        10, 1, Shape.Line,
        17,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Arc Lightning", "&*", SpellSubtype.Core,
        "#ff3", "#000",
        "Has an arc value of 3.",
        12, DmgType.Lightning,
        10, 1, Shape.Line,
        35,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Chain Lightning", "&/", SpellSubtype.Core,
        "#ff3", "#000",
        "Has a chain value of 4.",
        10, DmgType.Lightning,
        10, 1, Shape.Line,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Hypercharge", "^&", SpellSubtype.Core,
        "#ff6", "#000",
        "All damaged units take and deal 50% more Lightning damage for 16 turns.",
        6, DmgType.Lightning,
        6, 3, Shape.Circle,
        75,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Spark", "-*", SpellSubtype.Core,
        "#ff0", "#127",
        "Casts another core at the point this core was targeted.",
        1, DmgType.Lightning,
        12, 1, Shape.Diamond,
        -15,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Magic Missile", "=»", SpellSubtype.Core,
        "#f49", "#000",
        "",
        10, DmgType.Arcane,
        12, 1, Shape.Line,
        10,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Arcane Crush", "»«", SpellSubtype.Core,
        "#c4c", "#000",
        "Applies Stunned for 2 turns to any non-stunned unit taking damage from this core.",
        16, DmgType.Arcane,
        7, 1, Shape.Diamond,
        35,
        SpellTargeting.UnitTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Magical Explosion", "«#", SpellSubtype.Core,
        "#f49", "#000",
        "Deals Physical damage equal to this core's damage value at every tile affected.",
        22, DmgType.Arcane,
        10, 4, Shape.Diamond,
        30,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Void Laser", "»=", SpellSubtype.Core,
        "#c26", "#000",
        "Applies Polarity (Arcane) for 3 turns to any unit damaged by this core. This core is not restricted by line of sight.",
        40, DmgType.Arcane,
        10, 1, Shape.Line,
        160,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Conjure Spear", "->", SpellSubtype.Core,
        "#ddd", "#000",
        "",
        17, DmgType.Physical,
        12, 1, Shape.Line,
        25,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Conjure Bullet", "-=", SpellSubtype.Core,
        "#ddd", "#000",
        "Deals twice this core's damage value as Fire damage at the targeted location.",
        26, DmgType.Physical,
        14, 1, Shape.Line,
        60,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Sonic Boom", ">)", SpellSubtype.Core,
        "#ddd", "#000",
        "Has an arc value of 2. Applies Stunned for 1 turn to any non-stunned units taking Physical damage from this core.",
        4, DmgType.Physical,
        9, 2, Shape.Cone,
        80,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Lacerate", "X/", SpellSubtype.Core,
        "#fdd", "#000",
        "Every instance of damage to a unit caused by this core will also apply 1 turn of Bleed to that unit.",
        6, DmgType.Physical,
        7, 2, Shape.Circle,
        75,
        SpellTargeting.UnitTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Magnetic Launcher", ">=", SpellSubtype.Core,
        "#ddd", "#000",
        "Any unit in the area of effect of this core will take Physical damage equal to 20% of this core's damage value per tile of distance between them and the caster.",
        25, DmgType.Physical,
        64, 1, Shape.Line,
        200,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Ball of Skulls", "Q.", SpellSubtype.Core,
        "#99a", "#000",
        "Summons a Skeleton at the target position if it is empty.",
        8, DmgType.Dark,
        8, 2, Shape.Circle,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Mass Haunting", "O^", SpellSubtype.Core,
        "#99a", "#000",
        "Summons a Ghost at every empty tile this core affected.",
        12, DmgType.Dark,
        6, 2, Shape.Diamond,
        80,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Reinforce", "#!", SpellSubtype.Core,
        "#74a", "#000",
        "Any non-player unit with Dark affinity in this core's area of effect will be healed to full HP and gain access to Death Bolt.",
        0, DmgType.Dark,
        8, 3, Shape.Diamond,
        100,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Death Bolt", "#>", SpellSubtype.Core,
        "#74a", "#000",
        "",
        12, DmgType.Dark,
        10, 1, Shape.Line,
        20,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Turn Unwilling Dead", "#$", SpellSubtype.Core,
        "#74a", "#000",
        "If an enemy dies as a result of damage from this core, they will be reanimated on the caster's side. Their affinities are removed and replaced with Dark and Undead.",
        20, DmgType.Dark,
        3, 1, Shape.Circle,
        200,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Unknown Incantation", "!?", SpellSubtype.Core,
        "#e90", "#000",
        "\"This core will have a random bonus effect on cast that changes every time it is used by ANYONE.\nNext effect: [#4df]Nothing.[clear]\"",
        20, DmgType.Chaos,
        10, 2, Shape.Diamond,
        30,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Chromatic Shattering", "&{", SpellSubtype.Core,
        "#e90", "#000",
        "This core's damage type will randomly change to another damage type every time it is cast by ANYONE.",
        20, DmgType.Chaos,
        10, 1, Shape.Line,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Cone of Chaos", "%}", SpellSubtype.Core,
        "#e90", "#000",
        "Deals Fire or Lightning damage equal to this core's damage value at every tile affected.",
        12, DmgType.Chaos,
        8, 3, Shape.Cone,
        50,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Demonic Summoning", "%*", SpellSubtype.Core,
        "#b90", "#000",
        "Summons one of four random Demons (Fire, Ice, Primal, Brimstone) at the target position if it is empty.",
        20, DmgType.Chaos,
        6, 3, Shape.Circle,
        300,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Sacred Bolt", "*=", SpellSubtype.Core,
        "#ff9", "#000",
        "If the unit at the target position is Dark, Demon, Undead or Ghost, applies Stunned to them for 3 turns.",
        10, DmgType.Holy,
        12, 1, Shape.Line,
        20,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Shining Spear", "*/", SpellSubtype.Core,
        "#ff9", "#000",
        "Deals additional Physical damage equal to this core's damage value at every tile affected, as well as Holy damage if the unit is Dark, Demon, Undead or Ghost.",
        18, DmgType.Holy,
        12, 1, Shape.Line,
        60,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Angelic Chorus", "^*", SpellSubtype.Core,
        "#ff9", "#000",
        "All Holy units taking Holy damage from this core will be healed by an amount equal to twice this core's damage value.",
        15, DmgType.Holy,
        0, 5, Shape.Diamond,
        50,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Consecrate", "*\"", SpellSubtype.Core,
        "#fd9", "#000",
        "All Dark, Demon, Undead or Ghost units taking Holy damage from this core will also take an equal amount of Fire damage.",
        30, DmgType.Holy,
        0, 5, Shape.Square,
        100,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Apotheosis", "^^", SpellSubtype.Core,
        "#ffc", "#000",
        "Applies Invincible and Stunned for 10 turns to the caster, then summons two allied Seraphim and two allied Archangels in the closest available positions.",
        0, DmgType.Holy,
        0, 0, Shape.Diamond,
        400,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Mind Spike", "=}", SpellSubtype.Core,
        "#f9f", "#000",
        "Cannot damage allied units.",
        10, DmgType.Psychic,
        14, 1, Shape.Line,
        25,
        SpellTargeting.Positional,
        [Teams.ENEMY]
    ),

    core_spell(
        "Touch of Mindshattering", "}%", SpellSubtype.Core,
        "#f9f", "#000",
        "Applies Stunned for 4 turns to any non-stunned unit taking Psychic damage from this core.",
        8, DmgType.Psychic,
        1, 1, Shape.Diamond,
        140,
        SpellTargeting.UnitTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Memetic Virus", "}~", SpellSubtype.Core,
        "#f9f", "#000",
        "Has a chain value of 6. The damage value of this core is locked at 0. Cannot target or damage allied units.",
        0, DmgType.Psychic,
        7, 1, Shape.Line,
        80,
        SpellTargeting.UnitTarget,
        [Teams.ENEMY]
    ),

    core_spell(
        "Overwhelm", "~{", SpellSubtype.Core,
        "#f9f", "#000",
        "Applies 3 turns of Sleeping to any unit taking Psychic damage from this core.",
        12, DmgType.Psychic,
        6, 3, Shape.Cone,
        100,
        SpellTargeting.UnitTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Blink", ".-", SpellSubtype.Core,
        "#fcf", "#000",
        "Teleports the caster to the target position of this core after casting it, if it is empty.",
        0, DmgType.Psychic,
        6, 1, Shape.Diamond,
        30,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Teleport", ".!", SpellSubtype.Core,
        "#fcf", "#000",
        "Teleports the caster to the target position of this core after casting it, if it is empty.",
        0, DmgType.Psychic,
        20, 1, Shape.Diamond,
        80,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Disperse", ".?", SpellSubtype.Core,
        "#fcf", "#000",
        "All units taking Psychic damage from this core will be teleported to random empty positions within a 5 tile radius.",
        5, DmgType.Psychic,
        0, 4, Shape.Diamond,
        50,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Dimensional Rift", ".%", SpellSubtype.Core,
        "#f8b", "#000",
        "Teleports any unit in this core's area of effect to a random empty location on the map.",
        0, DmgType.Arcane,
        10, 4, Shape.Circle,
        70,
        SpellTargeting.SelfTargetPlusCaster,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Last Resort", "!!", SpellSubtype.Core,
        "#fff", "#000",
        "Sets the caster's current HP to 1 and removes 10% of their max HP.",
        200, DmgType.Physical,
        12, 3, Shape.Diamond,
        0,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Fireball with Trigger", "@\"", SpellSubtype.Core,
        "#e52", "#127",
        "Casts another core at the point this core was targeted.",
        10, DmgType.Fire,
        7, 3, Shape.Diamond,
        50,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Lightning Bolt with Trigger", "&>", SpellSubtype.Core,
        "#ff3", "#127",
        "Casts another core at the point this core was targeted.",
        13, DmgType.Lightning,
        10, 1, Shape.Line,
        42,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Magic Missile with Trigger", "=»", SpellSubtype.Core,
        "#f49", "#127",
        "Casts another core at the point this core was targeted.",
        10, DmgType.Arcane,
        12, 1, Shape.Line,
        35,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    modifier(
        "Damage Plus I", "D+", SpellSubtype.Stats,
        "#c44", "#03f",
        "Increases the core's damage value by 5.",
        15,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Damage Plus II", "D*", SpellSubtype.Stats,
        "#c44", "#03f",
        "Increases the core's damage value by 15.",
        40,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Damage Overcharge", "D!", SpellSubtype.Stats,
        "#f44", "#03f",
        "Sets the radius of the core to 1. The core's damage value is increased by 5 times its radius before this reduction.",
        70,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Radius Plus I", "R+", SpellSubtype.Stats,
        "#4cf", "#03f",
        "Increases the core's radius by 1.",
        20,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Radius Plus II", "R*", SpellSubtype.Stats,
        "#4cf", "#03f",
        "Increases the core's radius by 2.",
        30,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Range Plus I", "N+", SpellSubtype.Stats,
        "#4d4", "#03f",
        "Increases the core's range by 2.",
        12,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Range Plus II", "N*", SpellSubtype.Stats,
        "#4d4", "#03f",
        "Increases the core's range by 5.",
        20,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Orbital Mirroring", "N!", SpellSubtype.Stats,
        "#2f2", "#03f",
        "Increases the core's range by 64.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Projection", ">~", SpellSubtype.Stats,
        "#fff", "#03f",
        "Allows the core to ignore line of sight and collision for targeting and effects.",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Undercharging I", "P-", SpellSubtype.Stats,
        "#caa", "#03f",
        "Reduces the core's damage value by 7 and its radius by 1, but costs [#4df]negative mana[clear].",
        -25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Undercharging II", "p.", SpellSubtype.Stats,
        "#caa", "#03f",
        "Reduces the core's damage value by 13 and its radius by 2, but costs [#4df]negative mana[clear].",
        -60,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Power Focus", "#!", SpellSubtype.Stats,
        "#e6e", "#03f",
        "Reduces the core's range by 6, but increases its damage value by 25.",
        25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Unbounded Energy", "^M", SpellSubtype.Stats,
        "#6ff", "#03f",
        "Increases the core's damage value by 10% of the caster's current mana, but also makes it remove 10% of the caster's current mana on cast.",
        10,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Synergistic Arcana", "x+", SpellSubtype.Stats,
        "#e6e", "#03f",
        "Multiplies the effect of previous modifiers on the core's stats by 1.25x.",
        75,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Antisynergy", "x-", SpellSubtype.Stats,
        "#93f", "#03f",
        "Multiplies the effect of previous modifiers on the core's stats by 0.75x.",
        5,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Random Damage", "D?", SpellSubtype.Stats,
        "#fff", "#03f",
        "Modifies the core's damage value by a random number from -100 to 100.",
        33,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Zenith Arcana I", "X*", SpellSubtype.Stats,
        "#0ef", "#03f",
        "Increases the core's damage value by 50, its radius by 3 and its range by 8.",
        600,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Zenith Arcana II", "X#", SpellSubtype.Stats,
        "#4ff", "#03f",
        "Increases the core's damage value by 150, its radius by 5 and its range by 12.",
        2000,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Pain Catalyst I", "#+", SpellSubtype.Stats,
        "#f00", "#03f",
        "Increases the core's damage value by 5 for every 10% HP the caster is missing.",
        20,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Pain Catalyst II", "#*", SpellSubtype.Stats,
        "#f00", "#03f",
        "Increases the core's damage value by 15 and its radius by 1 for every 10% HP the caster is missing.",
        80,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Last Stand", "#!", SpellSubtype.Stats,
        "#f00", "#03f",
        "If the caster has less than 10% HP remaining, doubles the core's damage value, radius and range.",
        120,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Affinity Matching", "@+", SpellSubtype.Stats,
        "#fff", "#03f",
        "If the core's damage type is also one of the caster's affinities, multiplies its damage value by 1.5x.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Sympathetic Damage", "}+", SpellSubtype.Stats,
        "#d59", "#03f",
        "Multiplies the core's damage value by the caster's damage taken multiplier for the core's damage type.",
        240,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Strange Shuffle", "$?", SpellSubtype.Stats,
        "#e90", "#03f",
        "Swaps the core's radius and damage values...!",
        777,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Paradigm Shift", "$=", SpellSubtype.Stats,
        "#af0", "#03f",
        "Sets the core's radius to half its range value and its range value to twice its previous radius.",
        60,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Null", "0.", SpellSubtype.Stats,
        "#777", "#03f",
        "Sets the radius, range and damage value of the core to 0...!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Catch-up Damage", "=3", SpellSubtype.Stats,
        "#faa", "#03f",
        "Sets the core's damage to 33.",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Equalisation", "$O", SpellSubtype.Stats,
        "#88f", "#03f",
        "Redistributes the core's range, radius and damage value into the same proportions as the original core's values.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Vowel Lover", "A!", SpellSubtype.Stats,
        "#8f8", "#03f",
        "Grants the core +5 damage, +2 range and +1 radius for every vowel in its name.",
        99,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Trigger Finger", "%+", SpellSubtype.Stats,
        "#f66", "#03f",
        "Multiplies the core's damage value by 2x if the caster took damage last turn.",
        120,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Freezing Fire", "\"^", SpellSubtype.Damage,
        "#e52", "#32d",
        "Half of all Fire damage from the core is redealt as Ice damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Crystallized Flame", "\"«", SpellSubtype.Damage,
        "#e52", "#32d",
        "Half of all Fire damage from the core is redealt as Arcane damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chaotic Immolation", "\"%", SpellSubtype.Damage,
        "#e52", "#32d",
        "Half of all Fire damage from the core is redealt as Chaos damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Sacred Flames", "\"*", SpellSubtype.Damage,
        "#e52", "#32d",
        "Half of all Fire damage from the core is redealt as Holy damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Charged Ice", "^&", SpellSubtype.Damage,
        "#aff", "#32d",
        "Half of all Ice damage from the core is redealt as Lightning damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Crystalline Frost", "^«", SpellSubtype.Damage,
        "#aff", "#32d",
        "Half of all Ice damage from the core is redealt as Arcane damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Stifling Frost", "^#", SpellSubtype.Damage,
        "#aff", "#32d",
        "Half of all Ice damage from the core is redealt as Dark damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Arcane Conductance", "&«", SpellSubtype.Damage,
        "#ff3", "#32d",
        "Half of all Lightning damage from the core is redealt as Arcane damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Cracklevoid", "&#", SpellSubtype.Damage,
        "#ff3", "#32d",
        "Half of all Lightning damage from the core is redealt as Dark damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Heavenstrike", "&*", SpellSubtype.Damage,
        "#ff3", "#32d",
        "Half of all Lightning damage from the core is redealt as Holy damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Mind Bolts", "&{", SpellSubtype.Damage,
        "#ff3", "#32d",
        "Half of all Lightning damage from the core is redealt as Psychic damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Crystallized Sorcery", "»^", SpellSubtype.Damage,
        "#f49", "#32d",
        "Half of all Arcane damage from the core is redealt as Ice damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Dark Magic", "»#", SpellSubtype.Damage,
        "#f49", "#32d",
        "Half of all Arcane damage from the core is redealt as Dark damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Mind Magic", "»{", SpellSubtype.Damage,
        "#f49", "#32d",
        "Half of all Arcane damage from the core is redealt as Psychic damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Falcon Fist", "=\"", SpellSubtype.Damage,
        "#ddd", "#32d",
        "Half of all Physical damage from the core is redealt as Fire damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Lightning Fist", "=&", SpellSubtype.Damage,
        "#ddd", "#32d",
        "Half of all Physical damage from the core is redealt as Lightning damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Double Hit", "=2", SpellSubtype.Damage,
        "#ddd", "#32d",
        "All Physical damage from the core is redealt as Physical damage. This damage cannot trigger further effects.",
        240,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Shadow Strike", "=#", SpellSubtype.Damage,
        "#ddd", "#32d",
        "Half of all Physical damage from the core is redealt as Dark damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Pure Strike", "=*", SpellSubtype.Damage,
        "#ddd", "#32d",
        "Half of all Physical damage from the core is redealt as Holy damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Telekinesis", "={", SpellSubtype.Damage,
        "#ddd", "#32d",
        "Half of all Physical damage from the core is redealt as Psychic damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Blackflame", "#\"", SpellSubtype.Damage,
        "#95a", "#32d",
        "Half of all Dark damage from the core is redealt as Fire damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Deathly Frost", "#^", SpellSubtype.Damage,
        "#95a", "#32d",
        "Half of all Dark damage from the core is redealt as Ice damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Demonic Dark", "#%", SpellSubtype.Damage,
        "#95a", "#32d",
        "Half of all Dark damage from the core is redealt as Chaos damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Sacred Magic", "*«", SpellSubtype.Damage,
        "#ffa", "#32d",
        "Half of all Holy damage from the core is redealt as Arcane damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Apostasy", "*#", SpellSubtype.Damage,
        "#ffa", "#32d",
        "Half of all Holy damage from the core is redealt as Dark damage.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chromatic Catalyst", "O)", SpellSubtype.Damage,
        "#fff", "#32d",
        "Redeals all native damage from the core as every other damage type, split equally between each type.",
        300,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Null Magic", "-)", SpellSubtype.Damage,
        "#80a", "#32d",
        "Deals [#4df]negative[clear] damage equivalent to every instance of damage the core caused.",
        25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Hand of Fate", "O?", SpellSubtype.Damage,
        "#fff", "#32d",
        "Half of all native damage from the core is redealt as a random other damage type.",
        75,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chromatic Convergence", "O>", SpellSubtype.Damage,
        "#fff", "#32d",
        "Redeals half of the native damage from the core as the damage type the damaged unit is least resistant to, not including the core's own damage type.",
        360,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chromatic Divergence", "O<", SpellSubtype.Damage,
        "#fff", "#32d",
        "Redeals half of the native damage from the core as the damage type the damaged unit is most resistant to, not including the core's own damage type.",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Cosmetic Squares", "«»", SpellSubtype.Cosmetic,
        "#fff", "#61a",
        "Replaces the core's particle effect with white, long-lasting squares.",
        -25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Cosmetic Arrows", ">>", SpellSubtype.Cosmetic,
        "#fff", "#61a",
        "Replaces the core's particle effect with arrows of the damage type's colour.",
        -25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Alternate Fire", "\"2", SpellSubtype.Cosmetic,
        "#e52", "#61a",
        "Replaces the core's Fire damage particle effect with an alternate particle effect.",
        -30,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Alternate Ice", "^2", SpellSubtype.Cosmetic,
        "#aff", "#61a",
        "Replaces the core's Ice damage particle effect with an alternate particle effect.",
        -30,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "White Particles", "c/", SpellSubtype.Cosmetic,
        "#fff", "#61a",
        "Sets the colour of the core's particle effect to pure white.",
        -10,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Orange Particles", "c/", SpellSubtype.Cosmetic,
        "#fa0", "#61a",
        "Sets the colour of the core's particle effect to a delicious orange.",
        -10,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Alternate Physical", "-2", SpellSubtype.Cosmetic,
        "#ddd", "#61a",
        "Replaces the core's Physical damage particle effect with an alternate particle effect.",
        -30,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Hide Particles", "Xc", SpellSubtype.Cosmetic,
        "#fff", "#61a",
        "Disables the core's particle effect.",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Red Particles", "c/", SpellSubtype.Cosmetic,
        "#f00", "#61a",
        "Sets the colour of the core's particle effect to a deep red.",
        -30,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Yellow Particles", "c/", SpellSubtype.Cosmetic,
        "#ff0", "#61a",
        "Sets the colour of the core's particle effect to a shocking yellow.",
        -30,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Green Particles", "c/", SpellSubtype.Cosmetic,
        "#0f0", "#61a",
        "Sets the colour of the core's particle effect to a vibrant green.",
        -30,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Cyan Particles", "c/", SpellSubtype.Cosmetic,
        "#0ff", "#61a",
        "Sets the colour of the core's particle effect to a clear cyan.",
        -30,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Blue Particles", "c/", SpellSubtype.Cosmetic,
        "#68f", "#61a",
        "Sets the colour of the core's particle effect to a deep ocean blue.",
        -30,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Purple Particles", "c/", SpellSubtype.Cosmetic,
        "#c5c", "#61a",
        "Sets the colour of the core's particle effect to a regal purple.",
        -30,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Pink Particles", "c/", SpellSubtype.Cosmetic,
        "#f9f", "#61a",
        "Sets the colour of the core's particle effect to a cutesy pink.",
        -30,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Add Target Trigger", "+*", SpellSubtype.Trigger,
        "#ee0", "#26f",
        "Makes the core cast the next core at the point it was targeted.",
        25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Add Tile Trigger", "+x", SpellSubtype.Trigger,
        "#ee0", "#26f",
        "Makes the core cast a copy of the next core at every tile the core affected.",
        500,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Add Damage Trigger", "+;", SpellSubtype.Trigger,
        "#ee0", "#26f",
        "Makes the core cast a copy of the next core at every instance of damage the core caused.",
        400,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chromatic Target Trigger", "O*", SpellSubtype.Trigger,
        "#fff", "#26f",
        "Makes the core cast the next core at the point it was targeted, but also randomises the damage type of the core.",
        15,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chromatic Tile Trigger", "Ox", SpellSubtype.Trigger,
        "#fff", "#26f",
        "Makes the core cast a copy of the next core at every tile the core affected, but also randomises the damage type of the core.",
        450,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Unfair Damage Trigger", "!;", SpellSubtype.Trigger,
        "#fff", "#26f",
        "Makes the core cast a copy of the next core at every instance of damage the core caused, but sets the damage value of the core to 0.",
        250,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Unreliable Target Trigger", "?*", SpellSubtype.Trigger,
        "#fff", "#26f",
        "Makes the core cast the next core at the point it was targeted, has a 50% chance to set the core's radius to 0.",
        -25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Zenith Tile Trigger", "#x", SpellSubtype.Trigger,
        "#fff", "#26f",
        "Makes the core cast a copy of the next core at every tile the core affected, and doubles its radius.",
        2400,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Unfair Tile Trigger", "!x", SpellSubtype.Trigger,
        "#fff", "#26f",
        "Makes the core cast a copy of the next core at every every tile the core affected, but sets the radius of the core to 0.",
        250,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Untrigger", "-;", SpellSubtype.Trigger,
        "#fff", "#26f",
        "Removes the trigger from the core if there is one, applying a bonus based on the trigger type. [#4df]Target trigger[clear] grants +4 range, [#4df]damage trigger[clear] grants +15 damage value and [#4df]tile trigger[clear] grants +2 radius.",
        75,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Positional", "=>", SpellSubtype.Shape,
        "#fcf", "#441",
        "Allows the core to target [#4df]a position on the ground[clear].",
        90,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Unit Target", "=!", SpellSubtype.Shape,
        "#fcf", "#441",
        "Allows the core to target [#4df]a specific unit[clear].",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Self Target", "=O", SpellSubtype.Shape,
        "#fcf", "#441",
        "Allows the core to target [#4df]the area around the caster[clear].",
        25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Self Position", "=X", SpellSubtype.Shape,
        "#fcf", "#441",
        "Allows the core to target [#4df]at the caster's position[clear].",
        10,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Circle", "@@", SpellSubtype.Shape,
        "#fff", "#441",
        "Causes the core to affect tiles in a [#4df]circle shape[clear].",
        140,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Ring", "()", SpellSubtype.Shape,
        "#fff", "#441",
        "Causes the core to affect tiles in a [#4df]ring shape[clear].",
        40,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Line", "--", SpellSubtype.Shape,
        "#fff", "#441",
        "Causes the core to affect tiles in a [#4df]straight line[clear].",
        60,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Burst", "<>", SpellSubtype.Shape,
        "#fff", "#441",
        "Causes the core to affect tiles in a [#4df]burst[clear].",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Perpendicular Line", "-|", SpellSubtype.Shape,
        "#fff", "#441",
        "Causes the core to affect tiles in a [#4df]line perpendicular to the target[clear].",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Cone", "<=", SpellSubtype.Shape,
        "#fff", "#441",
        "Causes the core to affect tiles in a [#4df]cone shape[clear].",
        80,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Behind the Back", "<$", SpellSubtype.Multicast,
        "#fff", "#06b",
        "Casts a copy of the core behind the user.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Triangle Formation", "V$", SpellSubtype.Multicast,
        "#fff", "#06b",
        "Casts two more copies of the core to form an equilateral triangle shape.",
        200,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Square Formation", "X$", SpellSubtype.Multicast,
        "#fff", "#06b",
        "Casts three more copies of the core to form a square shape.",
        300,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chaotic Multicast x2", "!2", SpellSubtype.Multicast,
        "#faa", "#06b",
        "Adds 2 to the core's chaoscast value.",
        225,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chaotic Multicast x5", "!5", SpellSubtype.Multicast,
        "#faa", "#06b",
        "Adds 5 to the core's chaoscast value.",
        400,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Multicast x1", ">1", SpellSubtype.Multicast,
        "#6f6", "#06b",
        "Adds 1 to the core's multicast value.",
        125,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Multicast x2", ">2", SpellSubtype.Multicast,
        "#6f6", "#06b",
        "Adds 2 to the core's multicast value.",
        275,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Multicast x4", ">4", SpellSubtype.Multicast,
        "#6f6", "#06b",
        "Adds 4 to the core's multicast value.",
        350,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Multicast x8", ">8", SpellSubtype.Multicast,
        "#6f6", "#06b",
        "Adds 8 to the core's multicast value.",
        600,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Multicast x3 with Trigger", ";3", SpellSubtype.Multicast,
        "#4fc", "#06b",
        "Adds 3 to the core's multicast value and makes the core cast the next core at the point it was targeted.",
        350,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Micro Chain Spell", "/.", SpellSubtype.Multicast,
        "#fff", "#06b",
        "Adds 1 to the core's chain value.",
        125,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Micro Arc Spell", "*.", SpellSubtype.Multicast,
        "#ff0", "#06b",
        "Adds 1 to the core's arc value.",
        115,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Mini Chain Spell", "/-", SpellSubtype.Multicast,
        "#fff", "#06b",
        "Adds 2 to the core's chain value.",
        250,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Mini Arc Spell", "*-", SpellSubtype.Multicast,
        "#ff0", "#06b",
        "Adds 2 to the core's arc value.",
        230,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chain Spell", "/>", SpellSubtype.Multicast,
        "#fff", "#06b",
        "Adds 4 to the core's chain value.",
        350,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Arc Spell", "*>", SpellSubtype.Multicast,
        "#ff0", "#06b",
        "Adds 4 to the core's arc value.",
        320,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chaos Intensifier", "%+", SpellSubtype.Multicast,
        "#fcc", "#06b",
        "Sets the core's multicast value to 0. Increases the core's chaoscast value by the amount removed.",
        35,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chain Refocus", "/<", SpellSubtype.Multicast,
        "#aff", "#06b",
        "Sets the core's arc value to 0. Increases the core's chain value by 1.5x the amount removed.",
        120,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Arc Refocus", "*<", SpellSubtype.Multicast,
        "#af0", "#06b",
        "Sets the core's chain value to 0. Increases the core's arc value by 1.5x the amount removed.",
        120,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Duplicator Consumption", ">X", SpellSubtype.Multicast,
        "#9f9", "#06b",
        "Removes all forms of multicast from the core. Causes the core to restore the caster's mana by 25 on cast for each value removed.",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Blood Magic", "&+", SpellSubtype.Multicast,
        "#f44", "#06b",
        "Increases the core's multicast value by +1 per 20% HP the caster has. Causes the core to remove 0.5% of the caster's current HP when cast.",
        150,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Death Chain", "X/", SpellSubtype.Multicast,
        "#c8f", "#06b",
        "If a unit dies as a result of damage from the core, allows it to chain one more time.",
        130,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Subsurface Chain", "/~", SpellSubtype.Multicast,
        "#faf", "#06b",
        "Adds 6 to the core's chain value. Locks the damage value of the core to 0.",
        300,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Subsurface Arc", "*~", SpellSubtype.Multicast,
        "#f8c", "#06b",
        "Adds 6 to the core's arc value. Locks the damage value of the core to 0.",
        300,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Duplicator Amplification", ">+", SpellSubtype.Multicast,
        "#9f9", "#06b",
        "Removes all forms of multicast from the core. For each value removed, raises the core's radius by 1, its range by 2 and its damage value by 8.",
        250,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Conjure Mana", "O^", SpellSubtype.Misc,
        "#fff", "#265",
        "Restores 15 mana to the caster when the core is cast.",
        10,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Hardening Enchantment", "#-", SpellSubtype.Misc,
        "#fff", "#265",
        "Native damage caused by the core applies 3 turns of Resistance (native damage type)",
        40,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Intensifying Enchantment", "#+", SpellSubtype.Misc,
        "#fff", "#265",
        "Native damage caused by the core applies 4 turns of Polarity (native damage type)",
        75,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chromatic Impact", "O+", SpellSubtype.Misc,
        "#fff", "#265",
        "Any unit at the core's target position will receive Polarity of every damage type for 10 turns.",
        125,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Cleanse", "~-", SpellSubtype.Misc,
        "#fff", "#265",
        "Any unit damaged by the core will have all active effects removed from it.",
        40,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Magic Flare", ">\"", SpellSubtype.Misc,
        "#fff", "#265",
        "Changes the core's damage type to Fire.",
        240,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Formed Magic", ">=", SpellSubtype.Misc,
        "#fff", "#265",
        "Changes the core's damage type to Physical.",
        240,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Sanctity", ">*", SpellSubtype.Misc,
        "#fff", "#265",
        "Changes the core's damage type to Holy.",
        240,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Familiarity", ">@", SpellSubtype.Misc,
        "#fff", "#265",
        "Changes the core's damage type to the damage type the caster is most resistant against.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Vengeance", ">!", SpellSubtype.Misc,
        "#fff", "#265",
        "Changes the core's damage type to the damage type the caster is most weak against.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Affinity Attunement", ">A", SpellSubtype.Misc,
        "#fff", "#265",
        "Changes the core's damage type to the caster's first affinity which is also a damage type. If there are none, this does nothing.",
        300,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Heavy Impact", "#»", SpellSubtype.Misc,
        "#fff", "#265",
        "Any units on tiles affected by this core are pushed up to 2 tiles away from the core's cast position.",
        60,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Negative Space", "!O", SpellSubtype.Misc,
        "#fff", "#265",
        "Causes the core to affect all tiles in its range [#4df]except[clear] the ones in its original effect shape.",
        600,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Reconversion", "8~", SpellSubtype.Misc,
        "#fff", "#265",
        "Any non-player entity at the target position of the core will have all its affinities reversed. For example, [#e52]Fire[clear] will become [#aff]Ice[clear].",
        150,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Retarget: Self", "@o", SpellSubtype.Misc,
        "#faf", "#265",
        "Sets the target of the core to the caster's position and removes the caster's position from the core's area of effect.",
        25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Retarget: Enemy", "@e", SpellSubtype.Misc,
        "#faf", "#265",
        "Sets the target of the core to the closest enemy of the caster, within the original range of the core.",
        75,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Retarget: Ally", "@a", SpellSubtype.Misc,
        "#faf", "#265",
        "Sets the target of the core to the closest ally of the caster, within the original range of the core.",
        40,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Retarget: Weak", "@w", SpellSubtype.Misc,
        "#faf", "#265",
        "Sets the target of the core to the closest unit weakest to the core's damage type, within the original range of the core.",
        150,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Retarget: Strong", "@s", SpellSubtype.Misc,
        "#faf", "#265",
        "Sets the target of the core to the closest unit most resistant to the core's damage type, within the original range of the core.",
        60,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Retarget: Native", "@n", SpellSubtype.Misc,
        "#faf", "#265",
        "Sets the target of the core to the closest unit with an affinity matching the core's damage type, within the original range of the core.",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Retarget: Pushback", "@p", SpellSubtype.Misc,
        "#faf", "#265",
        "Moves the target of the core up to 3 tiles away from the caster.",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Retarget: Magnetism", "@m", SpellSubtype.Misc,
        "#faf", "#265",
        "Moves the target of the core up to 3 tiles towards the caster.",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Retarget: Compact", "@c", SpellSubtype.Misc,
        "#faf", "#265",
        "Moves the target of the core up to 2 tiles towards the position from which the core was cast.",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Retarget: Sparse", "@s", SpellSubtype.Misc,
        "#faf", "#265",
        "Moves the target of the core up to 2 tiles away from the position from which the core was cast.",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Retarget: Mysterious", "@?", SpellSubtype.Misc,
        "#faa", "#265",
        "Modifies the target of the core based on a mysterious set of rules indistinguishable from randomness.",
        176,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Spell Transference", "?>", SpellSubtype.Misc,
        "#fff", "#265",
        "The first core after this fragment is not cast. Instead, its special effects are transferred to the next core.",
        200,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Arcane Echo", ")2", SpellSubtype.Misc,
        "#fff", "#265",
        "All of the core's special effects will trigger twice.",
        150,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Spreading Arcana", ".O", SpellSubtype.Misc,
        "#fff", "#265",
        "Any of the core's special effects that would apply to the targeted position are also applied to every tile the core affects.",
        300,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Purity", "X.", SpellSubtype.Misc,
        "#fff", "#265",
        "The core will not trigger any of its special effects.",
        -75,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Unresolved Spell", "*?", SpellSubtype.Misc,
        "#fe9", "#265",
        "When this fragment is cast, it permanently becomes another random fragment.",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    core_spell(
        "Gun", "%=", SpellSubtype.Red,
        "#fff", "#f00",
        "",
        5000, DmgType.Physical,
        30, 1, Shape.Line,
        50,
        SpellTargeting.Positional,
        [Teams.ENEMY]
    ),

    modifier(
        "Uncontrolled Multicast x16", "!F", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "Adds 16 to the core's chaoscast value.",
        200,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    core_spell(
        "All Elements", "!!", SpellSubtype.Red,
        "#fff", "#f00",
        "all at once. testing",
        99999, DmgType.Physical,
        1, 40, Shape.Diamond,
        0,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Pea Spell", "!!", SpellSubtype.Red,
        "#fff", "#f00",
        "pea spell",
        73, DmgType.Chaos,
        10, 3, Shape.Circle,
        2,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "summon GUY", "@»", SpellSubtype.Red,
        "#fff", "#f00",
        "Summon \"Guy\" at the target position.",
        25, DmgType.Dark,
        10, 5, Shape.Circle,
        120,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Goop", "%;", SpellSubtype.Red,
        "#fff", "#f00",
        "Applies 999 turns of Poison to all units (all of them)",
        1, DmgType.Psychic,
        0, 1, Shape.Diamond,
        57,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    modifier(
        "Zenith Arcana III", "##", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "You're not strong enough for Zenith Arcana III.",
        1,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Zenith Arcana IV", "##", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "It's a little bit [#f00]too[clear] strong...",
        5000,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "208", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "209", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "210", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "211", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "212", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "213", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "214", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "215", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "216", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "217", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "218", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "219", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "220", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "221", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "222", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "223", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "224", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "225", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "226", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "227", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "228", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "229", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "230", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "231", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "232", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "233", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "234", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "235", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "236", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "237", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "238", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "239", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "240", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "241", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "242", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "243", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "244", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "245", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "246", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "247", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "248", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "249", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "250", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "251", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "252", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "253", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "254", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "255", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "256", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "257", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "258", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "259", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "260", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "261", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "262", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "263", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "264", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "265", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "266", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "267", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "268", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "269", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "270", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "271", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "272", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "273", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "274", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "275", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "276", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "277", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "278", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "279", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "280", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "281", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "282", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "283", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "284", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "285", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "286", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "287", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "288", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "289", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "290", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "291", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "292", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "293", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "294", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "295", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "296", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "297", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "298", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "299", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),


]