spells_list = [
    core_spell(
        "Fireball", "@\"", SpellSubtype.Core,
        "#e52", "#000",
        "",
        10, DmgType.Fire,
        7, 3, Shape.Diamond,
        25,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Searing Touch", "\">", SpellSubtype.Core,
        "#f52", "#000",
        "Doubles this core's final damage value.",
        40, DmgType.Fire,
        2, 1, Shape.Diamond,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Flame Nova", "X\"", SpellSubtype.Core,
        "#e84", "#000",
        "Gains 5 times this core's final radius as damage.",
        10, DmgType.Fire,
        0, 4, Shape.Diamond,
        50,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Flarefrost Beam", "=>", SpellSubtype.Core,
        "#e58", "#000",
        "Deals Ice damage equal to this core's damage value at every tile affected.",
        12, DmgType.Fire,
        9, 1, Shape.Line,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Cleansing Fire", "!\"", SpellSubtype.Core,
        "#fd4", "#000",
        "Half of all Fire damage caused by this core is redealt as Holy damage.",
        14, DmgType.Fire,
        8, 2, Shape.Diamond,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Ice Ball", "@>", SpellSubtype.Core,
        "#aff", "#000",
        "Deals Physical damage equal to this core's damage value at every tile affected.",
        6, DmgType.Ice,
        8, 2, Shape.Diamond,
        25,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Snap Freeze", "V^", SpellSubtype.Core,
        "#cff", "#000",
        "Applies Frozen for 3 turns to the unit at the target position.",
        6, DmgType.Ice,
        10, 1, Shape.Diamond,
        20,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Chilling Burst", "«>", SpellSubtype.Core,
        "#aff", "#000",
        "Applies Frozen for 2 turns to any unit taking Ice damage from this core.",
        9, DmgType.Ice,
        0, 7, Shape.Diamond,
        60,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Frostbite", "<^", SpellSubtype.Core,
        "#9bf", "#000",
        "Any instance of Ice damage caused by this core causes Dark damage equal to this core's damage value at the same position.",
        6, DmgType.Ice,
        7, 1, Shape.Diamond,
        50,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Absolute Zero", "^!", SpellSubtype.Core,
        "#bff", "#000",
        "Applies Freeze for 6 turns to the unit at the center of the burst.",
        20, DmgType.Ice,
        0, 12, Shape.Diamond,
        140,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Lightning Bolt", "&>", SpellSubtype.Core,
        "#ff3", "#000",
        "",
        13, DmgType.Lightning,
        10, 1, Shape.Line,
        17,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Arc Lightning", "&*", SpellSubtype.Core,
        "#ff3", "#000",
        "Has an arc value of 3.",
        12, DmgType.Lightning,
        10, 1, Shape.Line,
        35,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Chain Lightning", "&/", SpellSubtype.Core,
        "#ff3", "#000",
        "Has a chain value of 4.",
        10, DmgType.Lightning,
        10, 1, Shape.Line,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Hypercharge", "^&", SpellSubtype.Core,
        "#ff6", "#000",
        "All damaged units take and deal 50% more Lightning damage for 16 turns.",
        6, DmgType.Lightning,
        6, 3, Shape.Circle,
        75,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Spark", "-*", SpellSubtype.Core,
        "#ff0", "#127",
        "Casts another core at the point this core was targeted.",
        1, DmgType.Lightning,
        12, 1, Shape.Diamond,
        -15,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Magic Missile", "=»", SpellSubtype.Core,
        "#f49", "#000",
        "",
        10, DmgType.Arcane,
        12, 1, Shape.Line,
        10,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Arcane Crush", "»«", SpellSubtype.Core,
        "#c4c", "#000",
        "Applies Stunned for 2 turns to any non-stunned unit taking damage from this core.",
        16, DmgType.Arcane,
        7, 1, Shape.Diamond,
        35,
        SpellTargeting.UnitTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Magical Explosion", "«#", SpellSubtype.Core,
        "#f49", "#000",
        "Deals Physical damage equal to this core's damage value at every tile affected.",
        22, DmgType.Arcane,
        10, 4, Shape.Diamond,
        30,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Void Laser", "»=", SpellSubtype.Core,
        "#c26", "#000",
        "Applies Polarity (Arcane) for 3 turns to any unit damaged by this core. This core is not restricted by line of sight.",
        40, DmgType.Arcane,
        10, 1, Shape.Line,
        160,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Conjure Spear", "->", SpellSubtype.Core,
        "#ddd", "#000",
        "",
        17, DmgType.Physical,
        12, 1, Shape.Line,
        25,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Conjure Bullet", "-=", SpellSubtype.Core,
        "#ddd", "#000",
        "Deals twice this core's damage value as Fire damage at the targeted location.",
        26, DmgType.Physical,
        14, 1, Shape.Line,
        60,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Sonic Boom", ">)", SpellSubtype.Core,
        "#ddd", "#000",
        "Has an arc value of 2. Applies Stunned for 1 turn to any non-stunned units taking Physical damage from this core.",
        4, DmgType.Physical,
        9, 2, Shape.Cone,
        80,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Lacerate", "X/", SpellSubtype.Core,
        "#fdd", "#000",
        "Every instance of damage to a unit caused by this core will also apply 1 turn of Bleed to that unit.",
        6, DmgType.Physical,
        7, 2, Shape.Circle,
        75,
        SpellTargeting.UnitTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Magnetic Launcher", ">=", SpellSubtype.Core,
        "#ddd", "#000",
        "Any unit hit by this core will take Physical damage equal to 20% of this core's damage value per tile of distance between them and the caster.",
        25, DmgType.Physical,
        64, 1, Shape.Line,
        200,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Ball of Skulls", "Q.", SpellSubtype.Core,
        "#99a", "#000",
        "Summons a Skeleton at the target position if it is empty.",
        8, DmgType.Dark,
        8, 2, Shape.Circle,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Mass Haunting", "O^", SpellSubtype.Core,
        "#99a", "#000",
        "Summons a Ghost at every empty tile this core affected.",
        12, DmgType.Dark,
        6, 2, Shape.Diamond,
        80,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Reinforce", "#!", SpellSubtype.Core,
        "#74a", "#000",
        "Any non-player unit with Dark affinity in this core's area of effect will be healed to full HP and gain access to Dark Bolt.",
        0, DmgType.Dark,
        8, 3, Shape.Diamond,
        100,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Dark Bolt", "#>", SpellSubtype.Core,
        "#74a", "#000",
        "",
        12, DmgType.Dark,
        10, 1, Shape.Line,
        20,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Turn Unwilling Dead", "#$", SpellSubtype.Core,
        "#74a", "#000",
        "If an enemy dies as a result of damage from this core, they will be reanimated on the caster's side. Their affinities are removed and replaced with Dark and Undead.",
        20, DmgType.Dark,
        3, 1, Shape.Circle,
        200,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Unknown Incantation", "??", SpellSubtype.Core,
        "#e90", "#000",
        "\"This core will have a random bonus effect on cast that changes every time it is used by ANYONE.\nNext effect: [#4df]Nothing.[clear]\"",
        0, DmgType.Chaos,
        10, 2, Shape.Diamond,
        30,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Chromatic Shattering", "&{", SpellSubtype.Core,
        "#e90", "#000",
        "This core's damage type will randomly change to another damage type every time it is cast by ANYONE.",
        20, DmgType.Chaos,
        10, 1, Shape.Line,
        40,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Cone of Chaos", "%}", SpellSubtype.Core,
        "#e90", "#000",
        "Deals Fire or Lightning damage equal to this core's damage value at every tile affected.",
        12, DmgType.Chaos,
        8, 3, Shape.Cone,
        50,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Demonic Summoning", "%*", SpellSubtype.Core,
        "#b90", "#000",
        "Summons one of four random Demons (Fire, Ice, Lightning, Chaos) at the target position if it is empty.",
        20, DmgType.Chaos,
        6, 3, Shape.Circle,
        100,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Sacred Bolt", "*=", SpellSubtype.Core,
        "#ff9", "#000",
        "If the unit at the target position is Dark, Demon, Undead or Ghost, applies Stunned to them for 3 turns.",
        10, DmgType.Holy,
        12, 1, Shape.Line,
        20,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Shining Spear", "*/", SpellSubtype.Core,
        "#ff9", "#000",
        "Deals Physical damage equal to this core's damage value at every tile affected, as well as Holy damage if the unit is Dark, Demon, Undead or Ghost.",
        18, DmgType.Holy,
        12, 1, Shape.Line,
        60,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Angelic Chorus", "^*", SpellSubtype.Core,
        "#ff9", "#000",
        "All Holy units taking Holy damage from this core will be healed by an amount equal to twice this core's damage value.",
        15, DmgType.Holy,
        0, 5, Shape.Diamond,
        50,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Consecrate", "*\"", SpellSubtype.Core,
        "#fd9", "#000",
        "All Dark, Demon, Undead or Ghost units taking Holy damage from this core will also take an equal amount of Fire damage.",
        30, DmgType.Holy,
        0, 5, Shape.Square,
        100,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Apotheosis", "^^", SpellSubtype.Core,
        "#ffc", "#000",
        "Applies Invincible and Stunned for 10 turns to the caster, then summons two allied Seraphim and two allied Archangels in the closest available positions.",
        0, DmgType.Holy,
        0, 0, Shape.Diamond,
        400,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Mind Spike", "=}", SpellSubtype.Core,
        "#f9f", "#000",
        "Cannot damage allied units.",
        10, DmgType.Psychic,
        14, 1, Shape.Line,
        25,
        SpellTargeting.Positional,
        [Teams.ENEMY]
    ),

    core_spell(
        "Touch of Mindshattering", "}%", SpellSubtype.Core,
        "#f9f", "#000",
        "Applies Stunned for 5 turns to any unit taking Psychic damage from this core.",
        8, DmgType.Psychic,
        1, 1, Shape.Diamond,
        75,
        SpellTargeting.UnitTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Memetic Virus", "}~", SpellSubtype.Core,
        "#f9f", "#000",
        "Has a chain value of 6. The damage value of this core is locked at 0. Cannot target or damage allied units.",
        0, DmgType.Psychic,
        7, 1, Shape.Line,
        80,
        SpellTargeting.UnitTarget,
        [Teams.ENEMY]
    ),

    core_spell(
        "Overwhelm", "~{", SpellSubtype.Core,
        "#f9f", "#000",
        "Applies 3 turns of Sleeping to any unit taking Psychic damage from this core.",
        12, DmgType.Psychic,
        6, 3, Shape.Cone,
        100,
        SpellTargeting.UnitTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Blink", ".-", SpellSubtype.Core,
        "#fcf", "#000",
        "Teleports the caster to the target position of this core after casting it.",
        0, DmgType.Psychic,
        6, 1, Shape.Diamond,
        30,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Teleport", ".!", SpellSubtype.Core,
        "#fcf", "#000",
        "Teleports the caster to the target position of this core after casting it.",
        0, DmgType.Psychic,
        20, 1, Shape.Diamond,
        80,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Disperse", ".?", SpellSubtype.Core,
        "#fcf", "#000",
        "All units taking Psychic damage from this core will be teleported to random positions within a 5 tile radius.",
        5, DmgType.Psychic,
        0, 4, Shape.Diamond,
        50,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Dimensional Rift", ".%", SpellSubtype.Core,
        "#f8b", "#000",
        "Teleports any unit in this core's area of effect to a random location on the map.",
        0, DmgType.Arcane,
        10, 4, Shape.Circle,
        70,
        SpellTargeting.SelfTargetPlusCaster,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Last Resort", "!!", SpellSubtype.Core,
        "#fff", "#000",
        "Sets the caster's current HP to 1 and removes 10% of their max HP.",
        200, DmgType.Physical,
        12, 3, Shape.Diamond,
        0,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Fireball with Trigger", "@\"", SpellSubtype.Core,
        "#e52", "#127",
        "Casts another core at the point this core was targeted.",
        10, DmgType.Fire,
        7, 3, Shape.Diamond,
        50,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Lightning Bolt with Trigger", "&>", SpellSubtype.Core,
        "#ff3", "#127",
        "Casts another core at the point this core was targeted.",
        13, DmgType.Lightning,
        10, 1, Shape.Line,
        42,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Magic Missile with Trigger", "=»", SpellSubtype.Core,
        "#f49", "#127",
        "Casts another core at the point this core was targeted.",
        10, DmgType.Arcane,
        12, 1, Shape.Line,
        35,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    modifier(
        "Damage Plus I", "D+", SpellSubtype.Stats,
        "#c44", "#03f",
        "Increases the core's damage value by 5.",
        15,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Damage Plus II", "D*", SpellSubtype.Stats,
        "#c44", "#03f",
        "Increases the core's damage value by 15.",
        40,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Damage Overcharge", "D!", SpellSubtype.Stats,
        "#f44", "#03f",
        "Sets the radius of the core to 1. The core's damage value is increased by 5 times its radius before this reduction.",
        70,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Radius Plus I", "R+", SpellSubtype.Stats,
        "#4cf", "#03f",
        "Increases the core's radius by 1.",
        20,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Radius Plus II", "R*", SpellSubtype.Stats,
        "#4cf", "#03f",
        "Increases the core's radius by 2.",
        30,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Range Plus I", "N+", SpellSubtype.Stats,
        "#4d4", "#03f",
        "Increases the core's range by 2.",
        12,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Range Plus II", "N*", SpellSubtype.Stats,
        "#4d4", "#03f",
        "Increases the core's range by 5.",
        20,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Orbital Mirroring", "N!", SpellSubtype.Stats,
        "#2f2", "#03f",
        "Increases the core's range by 64.",
        160,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Projection", ">~", SpellSubtype.Stats,
        "#fff", "#03f",
        "Allows the core to ignore line of sight and collision for targeting and effects.",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Undercharging I", "P-", SpellSubtype.Stats,
        "#caa", "#03f",
        "Reduces the core's damage value by 7 and its radius by 1, but costs [#4df]negative mana[clear].",
        -25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Undercharging II", "p.", SpellSubtype.Stats,
        "#caa", "#03f",
        "Reduces the core's damage value by 13 and its radius by 2, but costs [#4df]negative mana[clear].",
        -60,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Power Focus", "#!", SpellSubtype.Stats,
        "#e6e", "#03f",
        "Reduces the core's range by 6, but increases its damage value by 25.",
        25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Unbounded Energy", "^M", SpellSubtype.Stats,
        "#6ff", "#03f",
        "Increases the core's damage value by 10% of the caster's current mana, but also makes it remove 10% of the caster's current mana on cast.",
        10,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Synergistic Arcana", "x+", SpellSubtype.Stats,
        "#e6e", "#03f",
        "Multiplies the effect of previous modifiers on the core's stats by 1.25x.",
        75,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Antisynergy", "x-", SpellSubtype.Stats,
        "#93f", "#03f",
        "Multiplies the effect of previous modifiers on the core's stats by 0.75x.",
        5,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Random Damage", "D?", SpellSubtype.Stats,
        "#fff", "#03f",
        "Increases the core's damage value by a random number from -100 to 100.",
        33,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Zenith Arcana I", "X*", SpellSubtype.Stats,
        "#0ef", "#03f",
        "Increases the core's damage value by 50, its radius by 3 and its range by 8.",
        600,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Zenith Arcana II", "X#", SpellSubtype.Stats,
        "#4ff", "#03f",
        "Increases the core's damage value by 150, its radius by 5 and its range by 12.",
        2000,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "68", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "69", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "70", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "71", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "72", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "73", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "74", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "75", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "76", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "77", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "78", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "79", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Freezing Fire", "\"^", SpellSubtype.Damage,
        "#e52", "#32d",
        "Half of all Fire damage from the core is redealt as Ice damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Crystallized Flame", "\"«", SpellSubtype.Damage,
        "#e52", "#32d",
        "Half of all Fire damage from the core is redealt as Arcane damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chaotic Immolation", "\"%", SpellSubtype.Damage,
        "#e52", "#32d",
        "Half of all Fire damage from the core is redealt as Chaos damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Sacred Flames", "\"*", SpellSubtype.Damage,
        "#e52", "#32d",
        "Half of all Fire damage from the core is redealt as Holy damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Charged Ice", "^&", SpellSubtype.Damage,
        "#aff", "#32d",
        "Half of all Ice damage from the core is redealt as Lightning damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Crystalline Frost", "^«", SpellSubtype.Damage,
        "#aff", "#32d",
        "Half of all Ice damage from the core is redealt as Arcane damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Stifling Frost", "^#", SpellSubtype.Damage,
        "#aff", "#32d",
        "Half of all Ice damage from the core is redealt as Dark damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Arcane Conductance", "&«", SpellSubtype.Damage,
        "#ff3", "#32d",
        "Half of all Lightning damage from the core is redealt as Arcane damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Cracklevoid", "&#", SpellSubtype.Damage,
        "#ff3", "#32d",
        "Half of all Lightning damage from the core is redealt as Dark damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Heavenstrike", "&*", SpellSubtype.Damage,
        "#ff3", "#32d",
        "Half of all Lightning damage from the core is redealt as Holy damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Mind Bolts", "&{", SpellSubtype.Damage,
        "#ff3", "#32d",
        "Half of all Lightning damage from the core is redealt as Psychic damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Crystallized Sorcery", "»^", SpellSubtype.Damage,
        "#f49", "#32d",
        "Half of all Arcane damage from the core is redealt as Ice damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Dark Magic", "»#", SpellSubtype.Damage,
        "#f49", "#32d",
        "Half of all Arcane damage from the core is redealt as Dark damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Mind Magic", "»{", SpellSubtype.Damage,
        "#f49", "#32d",
        "Half of all Arcane damage from the core is redealt as Psychic damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Falcon Fist", "=\"", SpellSubtype.Damage,
        "#ddd", "#32d",
        "Half of all Physical damage from the core is redealt as Fire damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Lightning Fist", "=&", SpellSubtype.Damage,
        "#ddd", "#32d",
        "Half of all Physical damage from the core is redealt as Lightning damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Double Hit", "=2", SpellSubtype.Damage,
        "#ddd", "#32d",
        "All Physical damage from the core is redealt as Physical damage. This damage cannot trigger further effects.",
        150,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Shadow Strike", "=#", SpellSubtype.Damage,
        "#ddd", "#32d",
        "Half of all Physical damage from the core is redealt as Dark damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Pure Strike", "=*", SpellSubtype.Damage,
        "#ddd", "#32d",
        "Half of all Physical damage from the core is redealt as Holy damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Telekinesis", "={", SpellSubtype.Damage,
        "#ddd", "#32d",
        "Half of all Physical damage from the core is redealt as Psychic damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Blackflame", "#\"", SpellSubtype.Damage,
        "#95a", "#32d",
        "Half of all Dark damage from the core is redealt as Fire damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Deathly Frost", "#^", SpellSubtype.Damage,
        "#95a", "#32d",
        "Half of all Dark damage from the core is redealt as Ice damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Demonic Dark", "#%", SpellSubtype.Damage,
        "#95a", "#32d",
        "Half of all Dark damage from the core is redealt as Chaos damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Sacred Magic", "*«", SpellSubtype.Damage,
        "#ffa", "#32d",
        "Half of all Holy damage from the core is redealt as Arcane damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Apostasy", "*#", SpellSubtype.Damage,
        "#ffa", "#32d",
        "Half of all Holy damage from the core is redealt as Dark damage.",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chromatic Catalyst", "O)", SpellSubtype.Damage,
        "#fff", "#32d",
        "Redeals all native damage from the core as every other damage type, split equally between each type.",
        200,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Null Magic", "-)", SpellSubtype.Damage,
        "#80a", "#32d",
        "Deals [#4df]negative[clear] damage equivalent to every instance of damage the core caused.",
        25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Hand of Fate", "O?", SpellSubtype.Damage,
        "#fff", "#32d",
        "Half of all native damage from the core is redealt as a random other damage type.",
        75,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chromatic Convergence", "O>", SpellSubtype.Damage,
        "#fff", "#32d",
        "Redeals half of the native damage from the core as the damage type the damaged unit is least resistant to, not including the core's own damage type.",
        250,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chromatic Divergence", "O<", SpellSubtype.Damage,
        "#fff", "#32d",
        "Redeals half of the native damage from the core as the damage type the damaged unit is most resistant to, not including the core's own damage type.",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "110", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "111", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "112", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "113", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "114", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "115", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "116", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "117", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "118", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "119", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "120", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "121", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "122", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "123", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "124", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Add Target Trigger", "+*", SpellSubtype.Trigger,
        "#cc0", "#26f",
        "Makes the core cast the next core at the point it was targeted.",
        25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Add Tile Trigger", "+x", SpellSubtype.Trigger,
        "#cc0", "#26f",
        "Makes the core cast a copy of the next core at every tile the core affected.",
        500,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Add Damage Trigger", "+;", SpellSubtype.Trigger,
        "#cc0", "#26f",
        "Makes the core cast a copy of the next core at every instance of damage the core caused.",
        400,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "128", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "129", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "130", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "131", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "132", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "133", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "134", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Positional", "=>", SpellSubtype.Shape,
        "#fcf", "#441",
        "Allows the core to target [#4df]a position on the ground[clear].",
        90,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Unit Target", "=!", SpellSubtype.Shape,
        "#fcf", "#441",
        "Allows the core to target [#4df]a specific unit[clear].",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Self Target", "=O", SpellSubtype.Shape,
        "#fcf", "#441",
        "Allows the core to target [#4df]the area around the caster[clear].",
        25,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Self Position", "=X", SpellSubtype.Shape,
        "#fcf", "#441",
        "Allows the core to target [#4df]at the caster's position[clear].",
        10,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Circle", "@@", SpellSubtype.Shape,
        "#fff", "#441",
        "Causes the core to affect tiles in a [#4df]circle shape[clear].",
        140,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Ring", "()", SpellSubtype.Shape,
        "#fff", "#441",
        "Causes the core to affect tiles in a [#4df]ring shape[clear].",
        40,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Line", "--", SpellSubtype.Shape,
        "#fff", "#441",
        "Causes the core to affect tiles in a [#4df]straight line[clear].",
        60,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Burst", "<>", SpellSubtype.Shape,
        "#fff", "#441",
        "Causes the core to affect tiles in a [#4df]burst[clear].",
        100,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Perpendicular Line", "-|", SpellSubtype.Shape,
        "#fff", "#441",
        "Causes the core to affect tiles in a [#4df]line perpendicular to the target[clear].",
        50,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Cone", "<=", SpellSubtype.Shape,
        "#fff", "#441",
        "Causes the core to affect tiles in a [#4df]cone shape[clear].",
        80,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Behind the Back", "<$", SpellSubtype.Multicast,
        "#fff", "#06b",
        "Casts a copy of the core behind the user.",
        120,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "146", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "147", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "148", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "149", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "150", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "151", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Multicast x4", ">4", SpellSubtype.Multicast,
        "#6f6", "#06b",
        "Adds 4 to the core's multicast value.",
        350,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "153", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "154", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "155", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "156", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "157", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "158", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chain Spell", "/>", SpellSubtype.Multicast,
        "#fff", "#06b",
        "Adds 4 to the core's chain value.",
        350,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Arc Spell", "*>", SpellSubtype.Multicast,
        "#ff0", "#06b",
        "Adds 4 to the core's arc value.",
        300,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "161", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "162", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "163", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "164", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "165", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "166", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "167", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "168", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "169", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Conjure Mana", "O^", SpellSubtype.Misc,
        "#fff", "#265",
        "Restores 15 mana to the caster when the core is cast.",
        10,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Hardening Enchantment", "#-", SpellSubtype.Misc,
        "#fff", "#265",
        "Native damage caused by the core applies 3 turns of Resistance (native damage type)",
        40,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Intensifying Enchantment", "#+", SpellSubtype.Misc,
        "#fff", "#265",
        "Native damage caused by the core applies 4 turns of Polarity (native damage type)",
        75,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Chromatic Impact", "O+", SpellSubtype.Misc,
        "#fff", "#265",
        "Any unit at the core's target position will receive Polarity of every damage type for 10 turns.",
        125,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "Cleanse", "~-", SpellSubtype.Misc,
        "#fff", "#265",
        "Any unit damaged by the core will have all active effects removed from it.",
        40,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "175", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "176", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "177", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "178", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "179", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "180", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "181", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "182", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "183", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "184", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "185", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "186", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "187", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "188", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "189", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "190", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "191", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "192", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "193", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "194", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "195", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "196", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "197", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "198", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "199", "??", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    core_spell(
        "Gun", "%=", SpellSubtype.Red,
        "#fff", "#f00",
        "",
        5000, DmgType.Physical,
        30, 1, Shape.Line,
        50,
        SpellTargeting.Positional,
        [Teams.ENEMY]
    ),

    modifier(
        "Uncontrolled Multicast x16", "!F", SpellSubtype.RedModifier,
        "#fff", "#f00",
        "Casts a copy of the core sixteen times, moving the target by a random number of tiles up to the core's final radius + 1 each time.",
        200,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    core_spell(
        "All Elements", "!!", SpellSubtype.Red,
        "#fff", "#f00",
        "all at once. testing",
        99999, DmgType.Physical,
        1, 40, Shape.Diamond,
        0,
        SpellTargeting.SelfTarget,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "Pea Spell", "!!", SpellSubtype.Red,
        "#fff", "#f00",
        "pea spell",
        73, DmgType.Chaos,
        10, 3, Shape.Circle,
        2,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    core_spell(
        "summon GUY", "@»", SpellSubtype.Red,
        "#fff", "#f00",
        "Summon \"Guy\" at the target position.",
        25, DmgType.Dark,
        10, 5, Shape.Circle,
        120,
        SpellTargeting.Positional,
        [Teams.ENEMY, Teams.PLAYER]
    ),

    modifier(
        "205", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "206", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "207", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "208", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "209", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "210", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "211", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "212", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "213", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "214", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "215", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "216", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "217", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "218", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "219", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "220", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "221", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "222", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "223", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "224", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "225", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "226", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "227", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "228", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "229", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "230", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "231", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "232", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "233", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "234", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "235", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "236", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "237", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "238", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "239", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "240", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "241", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "242", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "243", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "244", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "245", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "246", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "247", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "248", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "249", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "250", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "251", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "252", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "253", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "254", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "255", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "256", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "257", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "258", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "259", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "260", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "261", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "262", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "263", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "264", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "265", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "266", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "267", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "268", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "269", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "270", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "271", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "272", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "273", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "274", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "275", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "276", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "277", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "278", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "279", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "280", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "281", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "282", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "283", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "284", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "285", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "286", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "287", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "288", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "289", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "290", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "291", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "292", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "293", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "294", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "295", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "296", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "297", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "298", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "299", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),

    modifier(
        "300", "??", SpellSubtype.Red,
        "#fff", "#f00",
        "This core is corrupted and should not be here!",
        0,
        no_stats,
        no_target,
        no_hit,
        no_tiles,
    ),


]